#Pin constraints for addition of four 4-bit operands using carry save adder design for Basys 3
## Clock signal
set_property PACKAGE_PIN W5 [get_ports sys_clock]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports sys_clock]

# pushbutton BtnC
set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

##7 segment display
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

set_property PACKAGE_PIN U2 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]

## Switches
set_property PACKAGE_PIN V17 [get_ports {w0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {w0}]
set_property PACKAGE_PIN V16 [get_ports {w1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {w1}]
set_property PACKAGE_PIN W16 [get_ports {w2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {w2}]
set_property PACKAGE_PIN W17 [get_ports {w3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {w3}]
set_property PACKAGE_PIN W15 [get_ports {x0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {x0}]
set_property PACKAGE_PIN V15 [get_ports {x1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {x1}]
set_property PACKAGE_PIN W14 [get_ports {x2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {x2}]
set_property PACKAGE_PIN W13 [get_ports {x3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {x3}]
set_property PACKAGE_PIN V2 [get_ports {y0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y0}]
set_property PACKAGE_PIN T3 [get_ports {y1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y1}]
set_property PACKAGE_PIN T2 [get_ports {y2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y2}]
set_property PACKAGE_PIN R3 [get_ports {y3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y3}]
set_property PACKAGE_PIN W2 [get_ports {z0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {z0}]
set_property PACKAGE_PIN U1 [get_ports {z1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {z1}]
set_property PACKAGE_PIN T1 [get_ports {z2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {z2}]
set_property PACKAGE_PIN R2 [get_ports {z3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {z3}]
    
# LEDs
set_property PACKAGE_PIN U16 [get_ports {s0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s0}]
set_property PACKAGE_PIN E19 [get_ports {s1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s1}]
set_property PACKAGE_PIN U19 [get_ports {s2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s2}]
set_property PACKAGE_PIN V19 [get_ports {s3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s3}]
set_property PACKAGE_PIN W18 [get_ports {s4}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s4}]
set_property PACKAGE_PIN U15 [get_ports {s5}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s5}]
