#Pin constraints for XUPLIB 8 bit carry lookahead adder design for Basys 3
## Switches
set_property PACKAGE_PIN V17 [get_ports {a0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a0}]
set_property PACKAGE_PIN V16 [get_ports {a1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a1}]
set_property PACKAGE_PIN W16 [get_ports {a2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a2}]
set_property PACKAGE_PIN W17 [get_ports {a3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a3}]
set_property PACKAGE_PIN W15 [get_ports {a4}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a4}]
set_property PACKAGE_PIN V15 [get_ports {a5}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a5}]
set_property PACKAGE_PIN W14 [get_ports {a6}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a6}]
set_property PACKAGE_PIN W13 [get_ports {a7}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a7}]
set_property PACKAGE_PIN V2 [get_ports {b0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b0}]
set_property PACKAGE_PIN T3 [get_ports {b1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b1}]
set_property PACKAGE_PIN T2 [get_ports {b2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b2}]
set_property PACKAGE_PIN R3 [get_ports {b3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b3}]
set_property PACKAGE_PIN W2 [get_ports {b4}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b4}]
set_property PACKAGE_PIN U1 [get_ports {b5}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b5}]
set_property PACKAGE_PIN T1 [get_ports {b6}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b6}]
set_property PACKAGE_PIN R2 [get_ports {b7}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b7}]
    
# pushbutton C  
set_property PACKAGE_PIN U18 [get_ports {c_in}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {c_in}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {s0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s0}]
set_property PACKAGE_PIN E19 [get_ports {s1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s1}]
set_property PACKAGE_PIN U19 [get_ports {s2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s2}]
set_property PACKAGE_PIN V19 [get_ports {s3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s3}]
set_property PACKAGE_PIN W18 [get_ports {s4}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s4}]
set_property PACKAGE_PIN U15 [get_ports {s5}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s5}]
set_property PACKAGE_PIN U14 [get_ports {s6}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s6}]
set_property PACKAGE_PIN V14 [get_ports {s7}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s7}]
# LED 15    
set_property PACKAGE_PIN L1 [get_ports {c_out}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {c_out}]
